#Worker service
worker:
  service:
    count: 3

#Feign client
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic

## H2
#spring:
#  h2:
#    console:
#      enabled: true


spring:
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
# Postgresql Datasource
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: "jdbc:postgresql://database:5432/masterdb"
    username: postgres
    password: postgres